# -*- coding: utf-8 -*-
"""CNN+BiLSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqDFr3E3jQNRlYLPynccsUQ59LO34FfB
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, label_binarize
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
from itertools import cycle
import seaborn as sns
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# 1. Load dataset
df = pd.read_csv(r"C:\Users\anjali_jain\Downloads\emotion_dataset_cleaned.csv")

# 2. Split features and labels
X = df.drop('label', axis=1).values
y = df['label'].values

# 3. Encode labels
encoder = LabelEncoder()
y = encoder.fit_transform(y)

# 4. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=42, stratify=y
)

# 5. Reshape input for CNN+BiLSTM (add channel dimension)
X_train = X_train[..., np.newaxis]
X_test = X_test[..., np.newaxis]

# 6. Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

# 7. Create dataloaders
batch_size = 32
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size)

# 8. CNN + BiLSTM model
class CNNBiLSTM(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_classes, lstm_layers=1, dropout=0.3):
        super(CNNBiLSTM, self).__init__()
        self.conv1 = nn.Conv1d(in_channels=1, out_channels=64, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm1d(64)
        self.pool = nn.MaxPool1d(2)

        self.lstm = nn.LSTM(
            input_size=64,
            hidden_size=hidden_dim,
            num_layers=lstm_layers,
            batch_first=True,
            bidirectional=True
        )

        self.fc1 = nn.Linear((input_dim // 2) * 2 * hidden_dim, 64)
        self.dropout = nn.Dropout(dropout)
        self.fc2 = nn.Linear(64, num_classes)

    def forward(self, x):
        x = x.permute(0, 2, 1)  # [B, 1, F] -> [B, F, 1] -> needed format
        x = torch.relu(self.bn1(self.conv1(x)))  # [B, 64, F]
        x = self.pool(x)  # [B, 64, F//2]

        x = x.permute(0, 2, 1)  # [B, F//2, 64] -> time steps x features for LSTM
        out, _ = self.lstm(x)  # [B, F//2, 2*hidden_dim]
        out = out.contiguous().view(out.size(0), -1)  # Flatten

        out = torch.relu(self.fc1(out))
        out = self.dropout(out)
        out = self.fc2(out)
        return out

input_dim = X_train.shape[1]
num_classes = len(np.unique(y))
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = CNNBiLSTM(input_dim=input_dim, hidden_dim=32, num_classes=num_classes).to(device)

# 9. Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


# Early stopping parameters
patience = 10  # epochs to wait without improvement
best_val_loss = float('inf')
epochs_no_improve = 0
best_model_path = 'best_cnn_bilstm_model.pth'

# 10. Training loop
train_losses, val_losses, train_accs, val_accs = [], [], [], []
num_epochs = 100

for epoch in range(num_epochs):
    model.train()
    running_loss, correct, total = 0.0, 0, 0
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * inputs.size(0)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    train_loss = running_loss / len(train_loader.dataset)
    train_acc = correct / total
    train_losses.append(train_loss)
    train_accs.append(train_acc)

    # Validation
    model.eval()
    val_loss, correct, total = 0.0, 0, 0
    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            val_loss += loss.item() * inputs.size(0)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    val_loss /= len(test_loader.dataset)
    val_acc = correct / total
    val_losses.append(val_loss)
    val_accs.append(val_acc)

    print(f"Epoch {epoch+1}/{num_epochs} | Train Acc: {train_acc:.4f} | Val Acc: {val_acc:.4f}")
     # Early stopping check
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        epochs_no_improve = 0
        torch.save(model.state_dict(), best_model_path)
    else:
        epochs_no_improve += 1
        if epochs_no_improve >= patience:
            print(f"Early stopping triggered after {epoch+1} epochs. No improvement in validation loss for {patience} consecutive epochs.")
            break


# Load the best model before evaluation
if torch.cuda.is_available():
    model.load_state_dict(torch.load(best_model_path))
else:
    model.load_state_dict(torch.load(best_model_path, map_location=torch.device('cpu')))

# 11. Save training history
history_df = pd.DataFrame({'train_loss': train_losses, 'val_loss': val_losses,
                           'train_acc': train_accs, 'val_acc': val_accs})
history_df.to_csv("cnn_bilstm_training_history.csv", index=False)

# 12. Accuracy and loss plots
plt.figure()
plt.plot(train_accs, label='Train Accuracy')
plt.plot(val_accs, label='Validation Accuracy')
plt.legend()
plt.title("CNN + BiLSTM Accuracy")
plt.tight_layout()
plt.savefig("CNN_BiLSTM_accuracy_history.png")
plt.show()

plt.figure()
plt.plot(train_losses, label='Train Loss')
plt.plot(val_losses, label='Validation Loss')
plt.legend()
plt.title("CNN + BiLSTM Loss")
plt.tight_layout()
plt.savefig("CNN_BiLSTM_loss_history.png")
plt.show()

# 13. Evaluation
model.eval()
with torch.no_grad():
    y_score = []
    y_pred_classes = []
    y_true = []

    for inputs, labels in test_loader:
        inputs = inputs.to(device)
        outputs = model(inputs)
        probs = torch.softmax(outputs, dim=1)
        y_score.extend(probs.cpu().numpy())
        _, predicted = torch.max(probs, 1)
        y_pred_classes.extend(predicted.cpu().numpy())
        y_true.extend(labels.numpy())

y_score = np.array(y_score)
y_true = np.array(y_true)
y_pred_classes = np.array(y_pred_classes)

# 14. Confusion matrix
conf_matrix = confusion_matrix(y_true, y_pred_classes)
plt.figure(figsize=(10, 6))
sns.heatmap(conf_matrix / np.sum(conf_matrix, axis=0), annot=True, fmt='.2%',
            cmap='Blues', xticklabels=encoder.classes_, yticklabels=encoder.classes_)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('CNN + BiLSTM Confusion Matrix')
plt.tight_layout()
plt.savefig("CNN_BiLSTM_confusion_matrix.png")
plt.show()

# 15. Classification report
print("Classification Report CNN + BiLSTM:")
print(classification_report(y_true, y_pred_classes, target_names=encoder.classes_))

# 16. ROC curve
y_test_binarized = label_binarize(y_true, classes=np.arange(num_classes))
fpr, tpr, roc_auc = {}, {}, {}

for i in range(num_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

fpr["micro"], tpr["micro"], _ = roc_curve(y_test_binarized.ravel(), y_score.ravel())
roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])

plt.figure()
colors = cycle(['aqua', 'darkorange', 'cornflowerblue', 'green', 'red', 'purple', 'brown'])
for i, color in zip(range(num_classes), colors):
    plt.plot(fpr[i], tpr[i], color=color, lw=2,
             label='ROC curve of class {0} (area = {1:0.2f})'.format(encoder.classes_[i], roc_auc[i]))
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("CNN + BiLSTM ROC Curve")
plt.legend(loc="lower right")
plt.tight_layout()
plt.savefig("CNN_BiLSTM_ROC_Curve.png")
plt.show()

